from re import L


class Solution:
    def validPalindrome(self, s: str) -> bool:
        return CanPalindrome(s)
    
def CanPalindrome(s):
    lens = len(s)
    # left and right indexes
    l = 0
    r = lens - 1
    
    # check if pal
    # middle left and middle right indexes
    ml = l # ml is always >= l
    mr = r # mr is always <= r
    while ml < mr:
        if s[ml] != s[mr]:
            break
        ml += 1
        mr -= 1
    if ml >= mr:
        return True


    # check if we can remove one letter to make it a pal.
    while l < r:
        # test skipping left
        ml = l + 1
        mr = r
        while ml < mr:
            if s[ml] != s[mr]: # fail fast
                break
            ml += 1
            mr -= 1
        if ml >= mr: # skipping s[l] caused this to be a pal
            return True
        
        # test skipping right
        ml = l
        mr = r - 1
        while ml < mr: 
            if s[ml] != s[mr]: # fail fast
                break
            ml += 1
            mr -= 1
        if ml >= mr: # skipping s[r] caused this to be a pal
            return True

        if s[l] != s[r]:
            # these don't match and they will always be compared in subsequent tries, so fail out.
            return False
        
        l += 1
        r -= 1
    return False

print(Solution().validPalindrome("ezhcvjohmdvdmirolicyblpgrdcdrhnhmpywartuszaaufjggdbrsocwfwefslflplclltubpzocdqxcvcubxveqkosbrphmoqqlxjifmdumpbchbwxyaneernszgsrcgrbhzsastrmvjgsntvxicvnmkyjxcpgzfwlznuxrdlhrtwktpnfmkjqpugeavlayyhzevicsgzjydketwlrquqcukqyhzxkhrrtmmzfzqvpqmspkamkjgfblbdabddkiepzwseeakddjszyeapgoznixdghlnrhxzgegtlzfrarmpkfmdeitlhxogprzoijwptousenhiezrfsfosehemdhfnapfquzqicotafgjiwrsohhqybcvxysttxjbjxdfqyexibyfvxzywtssmsdmgjcyvljgykdgcyehfnnsoaexalrcqhirjhrmrzcyyzrslktrhxirfpwzhrgzlhgougvhulgybfemvpzqbnqlaxwbxsfqhyohsemnuzykpuyvxtogzeuhqsxsmlsshxdkgqynfhketiqmaumcrtgrlfejjkeckvumefotlhvdhguglzjskzgavatxgzohnpdcqkuayljhuvklksjdmxghqzbomubzeweobzvxvkzfprbpgokncbggdrbrfleskxduugbzevhkkwrsefmyzcygqjofysmwwfujsiypmcobcrhufwvvyabmucgvhobjrwgeqxgxsntvntlocnrnlkpaywpntfpvsohnfiefyzpqfvpcwubyarfuztiutkbdzxramhmbswtwyqvkvqwqiollsebluefuhsliquvjnsdskiqtscmrweqxvubxidacpoqmckdumlewuditgqrkbggkljbqptmiqfghwxbysrggsczwthugkwykmtbvebdbtfepxxvmqrsrnwfctcodouayrbxsqosbfsxvfqhhscvdxvpoaligfxfimkibtsdluwqeghjxuiomkogqehcfzsjescopcssqqpvfejkqivtakfdgsberbvpkcpvpyztxdzfikwgryfimffklvoolakxbwtatnixeltfgnlexemelrbsoybceetympurdhabnzcwnieywkalnmafeacgawfxiczkifxetwqjeylfahqfnlajlwsmetykiewdabsdopuuhoccoowliomgcpxvmtwzoswptzwkeutcpihhfezaapwdwckavdyrvkxghrqoymmtypokeztuucylmbcsccujmyivbgoqhxoswzoibxeujhjbckqtovbjldhoeclsjnnrnlbaigxwkwtqmdrtuhqkwxinzgsfqwrziknqsesmgsnpbfxtawrpdnfuyhiptnjgftutwmhrsjvkbjhclzraojwzdredtjdwbmtbvqtkllwyapjfcbcidhfqdohaxpqmwcogfpbfrnowyozzniomopvcuiezthjhjzoietqlnfljymeyiluhmmljplonghetegljiwuckrinyjieeconisbrcmobjssconvemclkpkflgnlbclqkcwwtabpymywpqbrcwoinjvumqoaqlozmhabahuqzetxcxpfhqpclduxtxwfouiistsgfowfbxyjoyvmmgproaiqelaxwfbqkeaaglgrpnoqjnsjmetsrhbyuzihanojmttaabifnxwwqdbkqlisnvmxhhkodnmxyemhbemgyixxfzrzidzckztvdttuqvvqrofrrdcojsngotsrtxxcjjhgymqgwljmwfufbniuenstjfibjkfqgqhhyfvqhvogfvicjubtkfyqlsshmuwelguuyjqthxjurckedpdbtbtdtsvkmbgfdhejouhfjeusfcridruwswnymvuhxpijyqatwiqjptcokigzrunzzycgzfbydwfkjunsgneasfbofrzfthndvkzygsvzdldebpsgvvdfezarggffmvzxgemfhlrpanvsinzatnxlsegsgohtqwicaimvvcrrqecqsjppmeuzprsvkpcqnmvtmvbbhutyohebrndraqmnboqzemwzwgjdkgxyajgnardaeturqtvsvnkpdopojluskcgprrybepdipidltqvhpumyososzxruimhrpzimbkdqryjdwljusqzerrdtawojzbrwyifvegbonaljsbnezhbprtshokkiiumerxjwpnueiqbenjxzrqxhtldtlcrqsiocsdaavcuasnhciykdkqrewdinluamktistjollnmnakhazphyhiunccziaaljawvykcsrrgvoocwonhdwmvyyavjytcgaggshsthcptqfbslcoxmulkrpzemcppeihsvylzocumigahkkmmursfkfxvqnhgiybaiyeknjlqyeqjscabggohazeukmrpmyffaerqhdiyaczlnidlwendgtipojfvyvqzpvuvmfruegmzouoijdbyikjjfzxntbseksqzgqtxpftxjirrqwjrzwcesjnqnyhnkyllyydhoqlmpazwdornuqeouunmqitwhyabkrzswwaoygvjptzewycrsbdimnbnyuvunibtsqveydfgtvdryxltawymxilsowvwakwxhrqsvmqgevbahpymfrtyikntkkndpvfqgbssubpoirkeppunhipkqbruequvbdvwwjizagfrfucurarawvfhmpjjybxefnybfdyleqfnpbmrkylkkqqnoyzlvnylfbijkrnqmklxnbzjospammuudekykgyljiyddblxfnhxlqvzpczkqhirdpddzvzvehxsyegosgmhonxkljrruuugubylibergbvhazfpsmbxpjunxbynvbvmirmsybujnfgeqzowphfbskyofywfjxccanjnwrbmfnlaqflkpcueipbhmnfxiwrhioeyqdvuryytfhzuwqfkibhrlyrkjvpqmixlxyxxmmwlbrspcuubqsybfjahulgjfyhitblumsofrrrqmncgkgadywwrmrckkgzwpowdzfraooqzbufdkrutgdgqemmxowstxbswepvmgmlvuyxcqhkozcymjzivrxxkcorqpiijdhbthqjarpdtvyypldqvkyyixvzdatgxlgmbqcaxcfpgwspipevltutduhqatolzmxsccyxynmydodkoxujgjfsogqmdbwxcnitaegqyxnddsgiqazexukvkxnxrcpraeyvhvcvjpyiltpzhxykoeilytbqyzhmweqlcunbvhjpqyhheorrelibudeqtbqvvdziywytyrcxtprklkrfwodfdcgssppqhftqrzbfrttnojroelwwvbdfrkmibpmxsmvpgresixsvqsaiyemyvrnkvkrcfpmsjbjmeymgdbcczqtdcfpxrepommjzmuhwsrbcjspczsyxlajzookmgakmzscaxixpjgnpqjcwodsljvmoobsdnvpsbmugmhvlncwkhjnavgaxsgohhvmjyisqnrwybvvwupijuvjfuaotlcacrlcyqsysvilbbzthhyvzdveqrpflgiwpschuaxqbwnqyhvuygducneaapcyobhflvwwrwkkjxptodjoywzjietkbizgmvpvofguyrfkynlsbpuipxjbraatgxdrgqbjhzksigbwaozcwugoxpeipzkmsrpxgwwxfpfyqrvpsqabyxjuwxmqkkuwerjqpkmtaoztkkxyavclcagrizohinolfugkwflbamoakgqmjvwqjvlkquelaaszgshwrlqpiirbcqnjjngvrjorwzjbuldmsrtupeyrxypfhhyftehjcobrktryyerbfxbnyfskqaakjehbsftercfinmcujzrexlsxoybafaqwxrdyxbonncxrhjmtrelvgudfkmeelvygcrbwfaxzgbxlauqeichxjwpyujjikdlwfckhkcvppceguafzrtbzalwglfjzrtegwhtoavxudabsrmuryubgeekckwiatzhtmtculnpcijzglkbzyaiedxdgvbnrkoukbjcrfusowhjvvzxlucuoktwcbyjxhxtffusythvooigwgwprtnekupafidujzbpbmllpgiwtjeepljjwaldgapsoiarwqydllmdlhcnfaxmllgvitonfchtduicsqdwhsuewvgjkxbmeuvjmdluysuzkajbqasgibjjvghtjhxmreycmsqedumkiqvpgttwhnwtrxgwullrqqlfocfqmxopfvowmrzyxxkcjvaezqrsotydhszxddmocnjwftybzifonqsxruccezhhwyestmgpthfyxcuelomzacbdorjuqjcoqydeijsakiephbvtwccfkvkkzfumcsbumetodjsgpxwnnwfjtywtzunvnwkvqkyetnwpasjadfldagxgalqoqyzrngrfxejapmmcmlmivvkxcviecbdseuxsbdlpbulkafwrnltywxgchyupsjpfkxgozhbsqcotqshekudtofysxzchhegxuquohjhoqyvrwsbaqxbsvozedldbmvcutsealtrctwxowpkowfjpzjbaxixexealwjvuaxbswgeofabtgzglrivuvwochfyguuvrvdusxgoaeresmubqkxmljichkdzbuwtlyngpjnsdocrrmsphxxptkpmvuhognqqtmopbrxavftkfbbyivpfcehstgqncvixllvcqtjuanfrifvmcqvsdgnotbqvbaocapzupnmtfkgarkjjiqfuohfpyvbpnitcvirmwbbmjebitlfkronvefxgbuzzqahzrsgsysyjauaunlfhclvagkpeohuwlkmlzqahbcfratkmuxofhqcjpxibftucscninykgsvrbqrrzmscskodeuhnvjzrauqiadfjsnibcbocbgtlhchxyzxcsyoojckcyltnqodnywbyzlplnlsesftfbplfkympbtcpjlgnimhfzjusmojjjmosittisomjjjomsujzfhmingljpctbpmykflpbftfseslnlplzybwyndoqntlyckcjooyscxzyxhchltgbcobcbinsjfdaiquarzjvnhuedokscsmzrrqbrvsgkynincscutfbixpjcqhfoxumktarfcbhaqzlmklwuhoepkgavlchflnuauajysysgsrzhaqzzubgxfevnorkfltibejmbbwmrivctinpbvypfhoufqijjkragkftmnpuzpacoabvqbtongdsvqcmvfirfnaujtqcvllxivcnqgtshecfpviybbfktfvaxrbpomtqqngohuvmpktpxxhpsmrrcodsnjpgnyltwubzdkhcijlmxkqbumsereaogxsudvrvuugyfhcowvuvirlgzgtbafoegwsbxauvjwlaexexixabjzpjfwokpwoxwtcrtlaestucvmbdldezovsbxqabswrvyqohjhouquxgehhczxsyfotdukehsqtocqsbhzogxkfpjspuyhcgxwytlnrwfaklubpldbsxuesdbceivcxkvvimlmcmmpajexfrgnrzyqoqlagxgadlfdajsapwnteykqvkwnvnuztwytjfwnnwxpgsjdotemubscmufzkkvkfccwtvbhpeikasjiedyqocjqujrodbcazmoleucxyfhtpgmtseywhhzeccurxsqnofizbytfwjncomddxzshdytosrqzeavjckxxyzrmwovfpoxmqfcoflqqrlluwgxrtwnhwttgpvqikmudeqsmcyermxhjthgvjjbigsaqbjakzusyuldmjvuembxkjgvweushwdqsciudthcfnotivgllmxafnchldmlldyqwraiospagdlawjjlpeejtwigpllmbpbzjudifapukentrpwgwgioovhtysufftxhxjbcwtkouculxzvvjhwosufrcjbkuokrnbvgdxdeiayzbklgzjicpnluctmthztaiwkckeegbuyrumrsbaduxvaothwgetrzjflgwlazbtrzfaugecppvckhkcfwldkijjuypwjxhciequalxbgzxafwbrcgyvleemkfdugvlertmjhrxcnnobxydrxwqafabyoxslxerzjucmnifcretfsbhejkaaqksfynbxfbreyyrtkrbocjhetfyhhfpyxryeputrsmdlubjzwrojrvgnjjnqcbriipqlrwhsgzsaaleuqklvjqwvjmqgkaomablfwkguflonihozirgaclcvayxkktzoatmkpqjrewukkqmxwujxybaqspvrqyfpfxwwgxprsmkzpiepxoguwczoawbgiskzhjbqgrdxgtaarbjxpiupbslnykfryugfovpvmgzibkteijzwyojdotpxjkkwrwwvlfhboycpaaencudgyuvhyqnwbqxauhcspwiglfprqevdzvyhhtzbblivsysqyclrcacltoaufjvujipuwvvbywrnqsiyjmvhhogsxagvanjhkwcnlvhmgumbspvndsboomvjlsdowcjqpngjpxixacszmkagmkoozjalxyszcpsjcbrswhumzjmmoperxpfcdtqzccbdgmyemjbjsmpfcrkvknrvymeyiasqvsxisergpvmsxmpbimkrfdbvwwleorjonttrfbzrqtfhqppssgcdfdowfrklkrptxcrytywyizdvvqbtqedubilerroehhyqpjhvbnuclqewmhzyqbtylieokyxhzptliypjvcvhvyearpcrxnxkvkuxezaqigsddnxyqgeatincxwbdmqgosfjgjuxokdodymnyxyccsxmzlotaqhudtutlvepipswgpfcxacqbmglxgtadzvxiyykvqdlpyyvtdprajqhtbhdjiipqrockxxrvizjmyczokhqcxyuvlmgmvpewsbxtswoxmmeqgdgturkdfubzqooarfzdwopwzgkkcrmrwwydagkgcnmqrrrfosmulbtihyfjgluhajfbysqbuucpsrblwmmxxyxlximqpvjkrylrhbikfqwuzhftyyruvdqyeoihrwixfnmhbpieucpklfqalnfmbrwnjnaccxjfwyfoyksbfhpwozqegfnjubysmrimvbvnybxnujpxbmspfzahvbgrebilybuguuurrjlkxnohmgsogeysxhevzvzddpdrihqkzcpzvqlxhnfxlbddyijlygkykeduummapsojzbnxlkmqnrkjibflynvlzyonqqkklykrmbpnfqelydfbynfexbyjjpmhfvwararucufrfgazijwwvdbvuqeurbqkpihnuppekriopbussbgqfvpdnkktnkiytrfmyphabvegqmvsqrhxwkawvwoslixmywatlxyrdvtgfdyevqstbinuvuynbnmidbsrcyweztpjvgyoawwszrkbayhwtiqmnuuoequnrodwzapmlqohdyyllyknhynqnjsecwzrjwqrrijxtfpxtqgzqskesbtnxzfjjkiybdjiouozmgeurfmvuvpzqvyvfjopitgdnewldinlzcayidhqreaffymprmkuezahoggbacsjqeyqljnkeyiabyighnqvxfkfsrummkkhagimucozlyvshieppcmezprklumxoclsbfqtpchtshsggagctyjvayyvmwdhnowcoovgrrsckyvwajlaaizccnuihyhpzahkanmnllojtsitkmaulnidwerqkdkyichnsaucvaadscoisqrcltdlthxqrzxjnebqieunpwjxremuiikkohstrpbhzenbsjlanobgevfiywrbzjowatdrrezqsujlwdjyrqdkbmizprhmiurxzsosoymuphvqtldipidpebyrrpgcksuljopodpknvsvtqruteadrangjayxgkdjgwzwmezqobnmqardnrbehoytuhbbvmtvmnqcpkvsrpzuemppjsqceqrrcvvmiaciwqthogsgeslxntaznisvnaprlhfmegxzvmffggrazefdvvgspbedldzvsgyzkvdnhtfzrfobfsaengsnujkfwdybfzgcyzznurzgikoctpjqiwtaqyjipxhuvmynwswurdircfsuejfhuojehdfgbmkvstdtbtbdpdekcrujxhtqjyuuglewumhsslqyfktbujcivfgovhqvfyhhqgqfkjbifjtsneuinbfufwmjlwgqmyghjjcxxtrstognsjocdrrforqvvquttdvtzkczdizrzfxxiygmebhmeyxmndokhhxmvnsilqkbdqwwxnfibaattmjonahizuybhrstemjsnjqonprglgaaekqbfwxaleqiaorpgmmvyojyxbfwofgstsiiuofwxtxudlcpqhfpxcxtezquhabahmzolqaoqmuvjniowcrbqpwymypbatwwckqlcblnglfkpklcmevnocssjbomcrbsinoceeijynirkcuwijlgetehgnolpjlmmhuliyemyjlfnlqteiozjhjhtzeiucvpomoinzzoywonrfbpfgocwmqpxahodqfhdicbcfjpaywllktqvbtmbwdjtderdzwjoarzlchjbkvjsrhmwtutfgjntpihyufndprwatxfbpnsgmsesqnkizrwqfsgznixwkqhutrdmqtwkwxgiablnrnnjslceohdljbvotqkcbjhjuexbiozwsoxhqogbviymjuccscbmlycuutzekopytmmyoqrhgxkvrydvakcwdwpaazefhhipctuekwztpwsozwtmvxpcgmoilwooccohuupodsbadweikytemswljalnfqhaflyejqwtexfikzcixfwagcaefamnlakwyeinwcznbahdrupmyteecbyosbrlemexelngftlexintatwbxkaloovlkffmifyrgwkifzdxtzypvpckpvbrebsgdfkatviqkjefvpqqsscpocsejszfcheqgokmoiuxjhgeqwuldstbikmifxfgilaopvxdvcshhqfvxsfbsoqsxbryauodoctcfwnrsrqmvxxpeftbdbevbtmkywkguhtwzcsggrsybxwhgfqimtpqbjlkggbkrqgtiduwelmudkcmqopcadixbuvxqewrmcstqiksdsnjvuqilshufeulbeslloiqwqvkvqywtwsbmhmarxzdbktuitzufraybuwcpvfqpzyfeifnhosvpftnpwyapklnrncoltnvtnsxgxqegwrjbohvgcumbayvvwfuhrcbocmpyisjufwwmsyfojqgyczymfesrwkkhvezbguudxkselfrbrdggbcnkogpbrpfzkvxvzboewezbumobzqhgxmdjsklkvuhjlyaukqcdpnhozgxtavagzksjzlgughdvhltofemuvkcekjjeflrgtrcmuamqitekhfnyqgkdxhsslmsxsqhuezgotxvyupkyzunmeshoyhqfsxbwxalqnbqzpvmefbygluhvguoghlzgrhzwpfrixhrtklsrzyyczrmrhjrihqcrlaxeaosnnfheycgdkygjlvycjgmdsmsstwyzxvfybixeyqfdxjbjxttsyxvcbyqhhosrwijgfatociqzuqfpanfhdmehesofsfrzeihnesuotpwjiozrpgoxhltiedmfkpmrarfzltgegzxhrnlhgdxinzogpaeyzsjddkaeeswzpeikddbadblbfgjkmakpsmqpvqzfzmmtrrhkxzhyqkucquqrlwtekdyjzgscivezhyyalvaegupqjkmfnptkwtrhldrxunzlwfzgpcxjykmnvcixvtnsgjvmrtsaszhbrgcrsgzsnreenayxwbhcbpmudmfijxlqqomhprbsokqevxbucvcxqdcozpbutllclplflsfewfwcosrbdggjfuaazsutrawypmhnhrdcdrgplbycilorimdvdmhojvchze"))